condense_wildcard_suffixes = true
edition = "2024"
fn_params_layout = "Compressed"
format_code_in_doc_comments = true
format_macro_matchers = true
hex_literal_case = "Lower"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
style_edition = "2024"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
